# Dataset Loading
Load your self-generated digits dataset from `dataset/labels.csv` and `dataset/images/*`.

In [ ]:
from pathlib import Path
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

PROJECT_DIR = Path.cwd()  # coursework.ipynb is in /project
LABELS_CSV = PROJECT_DIR / 'dataset' / 'labels.csv'

df = pd.read_csv(LABELS_CSV)
df.head()

cur dir :  /Users/raheemkhan/Documents/3rd-Year/Principles_of_AI/project
labels address :  /Users/raheemkhan/Documents/3rd-Year/Principles_of_AI/project/dataset/labels.csv
Rows in labels.csv: 1200


,filepath,label,writer_id,sheet_id,source_sheet,cell_index
0,dataset/images/0/ Khan_ 0_ sheet1_ 0.png,0,Khan,sheet1,Khan_0_sheet1.JPG,0
1,dataset/images/0/ Khan_ 0_ sheet1_ 1.png,0,Khan,sheet1,Khan_0_sheet1.JPG,1
2,dataset/images/0/ Khan_ 0_ sheet1_ 2.png,0,Khan,sheet1,Khan_0_sheet1.JPG,2
3,dataset/images/0/ Khan_ 0_ sheet1_ 3.png,0,Khan,sheet1,Khan_0_sheet1.JPG,3
4,dataset/images/0/ Khan_ 0_ sheet1_ 4.png,0,Khan,sheet1,Khan_0_sheet1.JPG,4


In [6]:
# Loading the dataset
X_list ,y_list = [],[]
for row in df.itertuples(index=False):
    img_path = row.filepath
    img = Image.open(img_path).convert("L").resize((28,28))
    X_list.append(np.array(img,dtype=np.uint8))
    y_list.append(int(row.label))

X = np.stack(X_list)
y = np.array(y_list, dtype=np.int64)

print('x : ', X)
print("y : ", y)

x :  [[[ 76 158 115 ... 172 155 140]
  [119 239 251 ... 251 249 206]
  [116 237 255 ... 255 255 221]
  ...
  [135 237 255 ... 255 255 255]
  [118 237 255 ... 255 255 255]
  [112 234 255 ... 255 255 255]]

 [[123 132 120 ... 181 150 146]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[105 110 133 ... 187 210 212]
  [113 210 251 ... 255 255 255]
  [115 221 255 ... 255 255 255]
  ...
  [149 246 255 ... 255 255 255]
  [174 255 255 ... 255 255 255]
  [171 255 255 ... 255 255 255]]

 ...

 [[250 250 250 ... 250 250 250]
  [250 250 250 ... 250 250 250]
  [250 250 250 ... 250 250 250]
  ...
  [250 250 250 ... 250 250 250]
  [250 250 250 ... 250 250 250]
  [250 223 206 ... 229 213 212]]

 [[250 250 250 ... 250 250 161]
  [250 250 250 ... 250 250 199]
  [250 250 250 ... 250 250 191]
  ...
  [250 250 250 ... 250 250 241]
  [250 251 245 ... 250 250 250]
  [206 206 198 ... 238 

In [ ]:
# Normalising the pixel values

